"""cleaned code, fixed minor mistakes

Revision ID: 2a0c3f88682f
Revises: c250dbfecfc6
Create Date: 2026-02-06 15:47:41.161227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0c3f88682f'
down_revision: Union[str, Sequence[str], None] = 'c250dbfecfc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
