"""Added 'city' field to the DBTemperature model

Revision ID: c250dbfecfc6
Revises: da83c71c4b29
Create Date: 2026-02-05 21:18:50.099101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c250dbfecfc6'
down_revision: Union[str, Sequence[str], None] = 'da83c71c4b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
