"""change models' names City -> DBCity, Temperature -> DBTemperature

Revision ID: da83c71c4b29
Revises: 1b13352e560f
Create Date: 2026-02-03 21:17:25.546695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da83c71c4b29'
down_revision: Union[str, Sequence[str], None] = '1b13352e560f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
